CREATE DATABASE PIZZAS;
USE PIZZAS;
 SELECT * FROM PIZZAS;
 SELECT * FROM PIZZA_TYPES;
 SELECT * FROM ORDERS;
 SELECT * FROM ORDER_DETAILS;
--  Basic:
-- 1. Retrieve the total number of orders placed.
SELECT COUNT(*) AS TOTAL_NO_OF_OREDRS_PLACED FROM ORDERS;
-- 2. Calculate the total revenue generated from pizza sales.
SELECT SUM(PRICE) FROM PIZZAS;
SELECT SUM(QUANTITY) FROM ORDER_DETAILS;
SELECT (CONCAT('$',(SELECT SUM(PRICE) FROM PIZZAS)* (SELECT SUM(QUANTITY) FROM ORDER_DETAILS))) AS TOTAL_REVANUE;
-- 3. Identify the highest-priced pizza.
SELECT MAX(PRICE) FROM PIZZAS;
SELECT PIZZA_ID, PRICE FROM PIZZAS HAVING PRICE=35.95;
-- 4. Identify the most common pizza size ordered.
SELECT SIZE, COUNT(PIZZA_ID) FROM PIZZAS GROUP BY SIZE HAVING COUNT(PIZZA_ID)=32;
SELECT COUNT(*) FROM PIZZAS;
-- 5. List the top 5 most ordered pizza types along with their quantities.
SELECT PIZZA_ID, QUANTITY FROM ORDER_DETAILS WHERE QUANTITY BETWEEN 3 AND 4; 
-- Intermediate:
-- 6. Join the necessary tables to find the total quantity of each pizza category ordered.
SELECT P.PIZZA_ID, PT.PIZZA_TYPE_ID, PT.CATEGORY, OD.QUANTITY FROM PIZZAS P JOIN ORDER_DETAILS OD ON P.PIZZA_ID = OD.PIZZA_ID  JOIN PIZZA_TYPES PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID; 
-- 7. Determine the distribution of orders by hour of the day.
SELECT HOUR(TIME) FROM ORDERS;
SELECT OD.PIZZA_ID, O.TIME  FROM ORDERS O JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID;
-- 8. Join relevant tables to find the category-wise distribution of pizzas.
SELECT P.PIZZA_ID, PT.CATEGORY, OD.QUANTITY, OD.DATE, OD.TIME FROM PIZZAS P JOIN ORDER_DETAIS OD ON P.PIZZA_ID= OD.PIZZA_ID JOIN PIZZA_TYPES PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID ;